name: Coverity

on:
  push:
    branches:
      - coverity_scan
  schedule:
    - cron: '0 20 * * *'

jobs:
  coverity:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package manager performance improvements
        if: ${{ runner.os != 'macOS' }}
        run: |
          sudo sh -c 'echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/02speedup'
          echo 'man-db man-db/auto-update boolean false' | sudo debconf-set-selections
          sudo dpkg-reconfigure man-db
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf
          sudo apt-get update

      - name: Install build dependencies
        run: |
          sudo apt-get install -y --no-install-recommends build-essential devscripts equivs quilt
          debian/rules debian/control
          sudo mk-build-deps -irt"apt-get -y --no-install-recommends" debian/control
          sudo mk-build-deps -irt"apt-get -y --no-install-recommends" scripts/ci/extra-packages.debian.control

      - name: Cache coverity tool
        uses: actions/cache@v2
        id: cache-coverity
        with:
          key: coverity-tool-cache-${{ runner.os }}
          path: coverity_tool.tar.gz

      - name: Build with Coverity
        run: |
          ./configure -with-rlm-python-bin=/usr/bin/python2.7
          make -j 8

      - name: Submit result
        run: |
          tar czf cov-int.tar.gz cov-int
          curl \
            --form token="$TOKEN" \
            --form email="freeradius-devel@lists.freeradius.org" \
            --form file=@cov-int.tar.gz \
            --form version="`cat VERSION`" \
            --form description="FreeRADIUS" \
            https://scan.coverity.com/builds?project=freeradius%2Ffreeradius-server
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
